relativeURLs = true
title = "Sung In Kim"
theme = "academimal-theme"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Ph.D. Candidate in Government, Harvard University"
    logo = "sunginkim.jpeg" 

[services]
  [services.googleAnalytics]
    ID = 'G-QX2YDMMHGT'
