relativeURLs = true
title = "Sung In Kim"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]
googleAnalytics = ""

[params]
    shortbio = "Ph.D. Candidate in Government, Harvard University"
    logo = "sunginkim.jpeg" 
    
